[pyprland]
plugins = ["scratchpads"]

[scratchpads]

[scratchpads.notes]
command = "obsidian"
class = "notes-float"
animation = ""
size = "50% 70%"
lazy = true

[scratchpads.term]
command = "ghostty --class=com.mitchellh.ghostty-float"
class = "ghostty-htop"
animation = ""
position = "5% 25%"
size = "50% 50%"
lazy = true
