[pyprland]
plugins = ["scratchpads"]

[scratchpads]

[scratchpads.notes]
command = "[float] obsidian"
class = "notes-float"
animation = "fromTop"
size = "50% 70%"
lazy = true

[scratchpads.term]
command = "ghostty --class=com.mitchellh.ghostty-float"
class = "ghostty-htop"
animation = "fromTop"
size = "50% 70%"
lazy = true
