{
  config,
  pkgs,
  lib,
  ...
}: {
  imports = [
    ./3d.nix
    ./cad.nix
    ./desktop.nix
    ./dev.nix
    ./dns.nix
    ./docker.nix
    ./flatpak.nix
    ./games.nix
    ./jupyter.nix
    ./laptop.nix
    ./mcc.nix
    ./officeWg.nix
    ./prometheus.nix
    ./twingate.nix
    ./videoEditing.nix
    ./virtualization.nix
    ./wine.nix
    ./wireshark.nix
    ./xMinimalDesktop.nix
    ./xMinimalDesktop.nix
  ];
}
