{
  config,
  pkgs,
  lib,
  ...
}: let
  cfg = config.roles.officeWg;
in {
  options.roles.officeWg = {
    enable = lib.mkEnableOption "Enable office wireguard";
    address = lib.mkOption {
      example = "192.168.250.2/32";
      type = lib.types.str;
      default = null;
      description = ''
        Wg ip address.
      '';
    };
    privateKeyFile = lib.mkOption {
      example = "/private/wireguard_key";
      type = lib.types.str;
      default = null;
      description = ''
        Private key file as generated by {command}`wg genkey`.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    networking.firewall.allowedUDPPorts = [51820];
    environment.etc = {
      "systemd/resolved.conf.d/vpn.conf".text = ''
        [Resolve]
        DNS=192.168.240.193 192.168.240.178
        Domains=~office.local-k8s.tech. ~office.vpn.
      '';
    };

    networking.wg-quick.interfaces = {
      officeWg0 = {
        address = [
          cfg.address
        ];
        listenPort = 51820;
        peers = [
          {
            allowedIPs = [
              "192.168.252.0/24"
              "192.168.251.0/24"
              "192.168.250.0/24"
              "192.168.240.0/24"
            ];
            endpoint = "46.254.69.178:51820";
            publicKey = "0Iko9oTbMfQRte2nAICUlB7wdvngFCWlTJkHs2ovl1U=";
          }
        ];
        privateKeyFile = cfg.privateKeyFile;
      };
    };
  };
}
