{ config, pkgs, lib, ... }:
let
  cfg = config.roles.officeWg;
in
{
  options.roles.officeWg = {
    enable = lib.mkEnableOption "Enable office wireguard";
    address = lib.mkOption {
      example = "192.168.250.2/32";
      type = lib.types.str;
      default = null;
      description = ''
        Wg ip address.
      '';
    };
    privateKeyFile = lib.mkOption {
      example = "/private/wireguard_key";
      type = lib.types.str;
      default = null;
      description = ''
        Private key file as generated by {command}`wg genkey`.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    networking.wg-quick.interfaces = {
      officeWg0 = {
        address = [
          cfg.address
        ];
        peers = [
          {
            allowedIPs = [
              "192.168.250.0/24,192.168.240.0/24"
            ];
            endpoint = "46.254.69.178:51820";
            publicKey = "0Iko9oTbMfQRte2nAICUlB7wdvngFCWlTJkHs2ovl1U=";
          }
        ];
        dns = [
          "192.168.240.193"
          "192.168.240.178"
        ];
        privateKeyFile = cfg.privateKeyFile;
      };
    };
  };
}

